### ISSUE TITLE
Add Donut Image to HTML

### ISSUE THREAD

**Issue by erodriguez541** [erodriguez541/donutProject#4]

**Comment by Christilea** [comment]
<img src="C:\Users\chris\OneDrive\Pictures\donut12.jpg" alt="donut">
A simple pic for now. I am still working on this.

**Comment by Christilea** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donut</title>
</head>
<body>
    <img src="C:\Users\chris\OneDrive\Pictures\donut12.jpg" alt="donut">
</body>
</html>
